### ISSUE TITLE
error with kmos view command

### ISSUE THREAD

**Issue by Abel-Ding** [jmlorenzi/intro2kmos#1]
### Expected behavior
run thekMC model about CO adsorption and desorption according to the tutorials: A first kMC Model- the API way (http://kmos.readthedocs.io/en/latest/tutorials/index.html)
### Actual behavior

I installed the kmos and the dependencies on ubuntu 16.04, and learn the tutorials "A first kMC Model-the API way"

while, after I export the xml, and try to view the model, it rised an TypeError, the error info is shown as followed:
```
abel@Abel:~/CL-SMR-KMC/kmos-learn/myfirst_kmc_local_smart$ kmos view
Traceback (most recent call last):
  File "/usr/local/bin/kmos", line 21, in <module>
    main()
  File "/home/abel/.local/lib/python2.7/site-packages/kmos/cli.py", line 426, in main
    view.main(steps_per_frame=options.steps_per_frame)
  File "/home/abel/.local/lib/python2.7/site-packages/kmos/view.py", line 452, in main
    viewer = KMC_Viewer(model, steps_per_frame=steps_per_frame)
  File "/home/abel/.local/lib/python2.7/site-packages/kmos/view.py", line 398, in __init__
    self.vbox, self.window)
  File "/home/abel/.local/lib/python2.7/site-packages/kmos/view.py", line 174, in __init__
    View.__init__(self, self.vbox, rotations)
TypeError: __init__() takes exactly 2 arguments (3 given)
```
It seems to be related to the ase.view, but I don't know how to deal with it. 
How could I fix this problem? Did I do something wrong in installation?
Looking forward to your solution and suggestion.

[//]: # (Besides the text description, include any screenshot(s) that help us visualize the issue you're facing)
```
abel@Abel:~/CL-SMR-KMC/kmos-learn/myfirst_kmc_local_smart$ kmos view
Traceback (most recent call last):
  File "/usr/local/bin/kmos", line 21, in <module>
    main()
  File "/home/abel/.local/lib/python2.7/site-packages/kmos/cli.py", line 426, in main
    view.main(steps_per_frame=options.steps_per_frame)
  File "/home/abel/.local/lib/python2.7/site-packages/kmos/view.py", line 452, in main
    viewer = KMC_Viewer(model, steps_per_frame=steps_per_frame)
  File "/home/abel/.local/lib/python2.7/site-packages/kmos/view.py", line 398, in __init__
    self.vbox, self.window)
  File "/home/abel/.local/lib/python2.7/site-packages/kmos/view.py", line 174, in __init__
    View.__init__(self, self.vbox, rotations)
TypeError: __init__() takes exactly 2 arguments (3 given)
```

### Steps to reproduce the issue
1.
2.
3.

### System information

- result of `kmos version`, operating system, version, python version, possibly link to model file

```
gfortran version (4:5.3.1-1ubuntu1).
python-dev iversion (2.7.11-1).
python-glade2 version (2.24.0-4ubuntu1).
python-lxml version (3.5.0-1build1).
python-numpy version (1:1.11.0-1ubuntu1).
python-kiwi version (1.9.22-4).
python-matplotlib version (1.5.1-1ubuntu1).
python-pygoocanvas version (0.14.1-1.1ubuntu1).
gazpacho version (0.7.2-3).

abel@Abel:~/CL-SMR-KMC/kmos-learn/myfirst_kmc_local_smart$ ase info
platform        Linux-4.4.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
python-2.7.12   /usr/bin/python
ase-3.15.0b1    /usr/local/lib/python2.7/dist-packages/ase-3.15.0b1-py2.7.egg/ase/
numpy-1.11.0    /usr/lib/python2.7/dist-packages/numpy/
scipy-0.17.0    /usr/lib/python2.7/dist-packages/scipy/
```
[//]: # (If you experienced crashes, segfaults please also include a stacktrace below.)

**Comment by jmlorenzi** [comment]
Hi Abel,

There's no need to duplicate this issue, once in the main kmos repo is enough. I will be replying there, because it is not directly related to this kmos learning material.

Best
Juan
